# -*- coding: utf-8 -*-
"""TUBES KECEBUT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bOlOxwR0wrMNT-DgNtz13YCeB5xgnAUK
"""

# STEP 1: IMPORT LIBRARY DAN LOAD DATASET
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Membaca dataset
df = pd.read_csv('dataset_sms_spam_v2.csv')

print(f"Jumlah Total Data Terbaca: {df.shape[0]} baris.")
print("\n--- Mengintip 5 Data Teratas ---")
display(df.head())

# STEP 2: PREPROCESSING (Mengubah Teks ke Angka)
X = df['Teks']
y = df['label']

# Membagi data menjadi: 80% Latih (Train) dan 20% Uji (Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Transformasi teks SMS ke angka numerik dengan TF-IDF
tfidf = TfidfVectorizer()
X_train_transformed = tfidf.fit_transform(X_train)
X_test_transformed = tfidf.transform(X_test)

print("\n[INFO] Tahap Preprocessing Teks Berhasil!")

# STEP 3 & 4: TRAINING & TESTING MODEL
model = MultinomialNB()
model.fit(X_train_transformed, y_train)
y_pred = model.predict(X_test_transformed)

# STEP 5: EVALUASI & GRAFIK
akurasi = accuracy_score(y_test, y_pred)
print("\n==========================================")
print(f"AKURASI MODEL DETEKSI SPAM AI: {akurasi * 100:.2f}%")
print("==========================================\n")

# Membuat dan menampilkan Grafik Confusion Matrix
label_urut = ['normal', 'penipuan', 'promo']
cm = confusion_matrix(y_test, y_pred, labels=label_urut)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_urut, yticklabels=label_urut)
plt.title('Grafik Hasil Evaluasi: Confusion Matrix Klasifikasi SMS')
plt.xlabel('Tebakan Model AI')
plt.ylabel('Jawaban Asli Lapangan')
plt.savefig('confusion_matrix_hasil.png', bbox_inches='tight')
plt.show()

# STEP 6: LIVE DEMO INTERAKTIF
print("\n========================================================")
print("======================= UJI SMS ========================")
print("========================================================")
print("Ketik pesan SMS di bawah untuk diuji oleh AI.")
print("Ketik kata 'selesai' jika ingin menghentikan demo.\n")

while True:
    # Menerima input langsung dari keyboard
    sms_kamu = input("Masukkan teks SMS baru: ")

    # Cek apakah user ingin menyudahi program
    if sms_kamu.strip().lower() == 'selesai':
        print("\n[INFO] UJI SMS dihentikan. Terima kasih!")
        break

    # Jika input kosong, diminta ketik ulang
    if not sms_kamu.strip():
        print("Pesan tidak boleh kosong, silakan ketik sesuatu.\n")
        continue

    # Proses mengubah ketikan baru menjadi angka numerik
    sms_kamu_transformed = tfidf.transform([sms_kamu])

    # AI menebak kategori SMS
    hasil_tebakan = model.predict(sms_kamu_transformed)[0]

    # Cetak hasil prediksi secara real-time
    print(f"-> Analisis Kategori Model AI: 【 {hasil_tebakan.upper()} 】")
    print("-" * 50 + "\n")